export interface Products {
  _id?: string,
  seq?: number,
  name?: string,
  nameAr?: string,
  description?: string,
  descriptionAr?: string,
  category?: string,
  categoryAr?: string,
  price?: number,
  priceAfterDiscount?: number,
  discount?: number,
  image?: string,
  addedDate?: Date,
}
